### ISSUE TITLE
Not showing at all..?

### ISSUE THREAD

**Issue by ezkay** [peiche/fluidbox-wp#3]
Hey man! 
Thanks for this Plugin! Should be really awesome, but somehow nothing shows up. On any Theme. When i click an image, it just opens the image alone as a normal link. 

Not sure if that is something for your side or Terry..

(Using Wordpress 4.2.2)

**Comment by peiche** [comment]
@ezkay Right now, the plugin is set to target links that contain the property `rel="lightbox"`, so if your image links don't have that, then they won't work. I had planned on making this an option of the plugin to be user-configurable, but I never got around to it.

You can always change this to suit your needs. The file is located at `js/fluidbox.custom.js` in the plugin directory.

**Comment by ezkay** [comment]
sorry man! it was my mistake! -.- somehow first i had left a `rel="lightbox"` from an old plugin. now the rel is gone. will tweek my theme or the

**Comment by ezkay** [comment]
Thanks for getting back so fast! Sorry man, it was my mistake! 
Somehow first i had left a `rel="lightbox"`from an old plugin! Will try to tweek my theme or the `js/fluidbox.custom.js`. Thank you!
