### ISSUE TITLE
Wrong Source of js files

### ISSUE THREAD

**Issue by akrai24** [peiche/fluidbox-wp#6]
the js file structure is this
js
 -src
    -fluidbox-custom.js
-jquery.fluidbox.min.js

but the script is enqueued as this
wp_enqueue_script( 'jquery_fluidbox', plugins_url( 'js/src/jquery.fluidbox.min.js', __FILE__ ), array( 'jquery' ), true );
    wp_enqueue_script( 'jquery_fluidboxcustom', plugins_url( 'js/fluidbox-custom.js', __FILE__ ), array( 'jquery_fluidbox' ), true );

**Comment by djmtype** [comment]
Right, the paths are incorrect.
